services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'agency-os-rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rmq_lib:/var/lib/rabbitmq
      - rmq_log:/var/log/rabbitmq
    restart: always

  postegres:
    image: postgres:13.14-alpine
    container_name: 'agency-os-postegres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgresws
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

volumes:
  pg_data:
  rmq_lib:
  rmq_log:
  http-gateway-node-modules:
